version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "build build build"
      - run: sleep 25
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "test test test"
      - run: sleep 25

